INSERT INTO REGIONS (name, latitude, longitude, description) VALUES
	('Afrique', -6.369, 34.888, 'Savanes, forêts tropicales et déserts abritant une faune emblématique.'),
	('Amérique du Sud', -8.783, -55.491, 'Amazonie et Andes, riche biodiversité tropicale.'),
	('Amérique du Nord', 45.0, -100.0, 'Forêts boréales, plaines et régions arctiques.'),
	('Asie', 34.047, 100.620, 'Himalaya, forêts tropicales et steppes.'),
	('Océanie', -25.274, 133.775, 'Australie et îles du Pacifique, faune unique et endémique.'),
	('Antarctique', -75.250, -0.071, 'Océan Austral et banquise, faune marine adaptée au froid extrême.'),
	('Europe', 54.526, 15.2551, 'Forêts tempérées et massifs montagneux, faune boréale et alpine.'),
	('Océans mondiaux', 0.0, -160.0, 'Ensemble des océans du globe, habitat des grandes espèces marines migratrices.');

INSERT INTO SPECIES (name_common, name_scientific, kingdom, phylum, class, habitat, diet, conservation_status, population_trend, description, image_url) VALUES
	('Lion', 'Panthera leo', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Carnivore', 'VU', 'Decreasing', 'Grand félin social vivant en troupes, prédateur apex des savanes africaines.', 'https://source.unsplash.com/800x600/?lion,wildlife'),
	('Léopard d''Afrique', 'Panthera pardus pardus', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Carnivore', 'VU', 'Decreasing', 'Félin solitaire et opportuniste, excellent grimpeur qui hisse ses proies dans les arbres.', 'https://source.unsplash.com/800x600/?l%C3%A9opard%20dafrique,wildlife'),
	('Guépard', 'Acinonyx jubatus', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Carnivore', 'VU', 'Decreasing', 'Le mammifère terrestre le plus rapide, capable de pointes à plus de 100 km/h.', 'https://source.unsplash.com/800x600/?gu%C3%A9pard,wildlife'),
	('Éléphant d''Afrique', 'Loxodonta africana', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'EN', 'Decreasing', 'Le plus grand mammifère terrestre, vivant en groupes matriarcaux structurés.', 'https://source.unsplash.com/800x600/?%C3%A9l%C3%A9phant%20dafrique,wildlife'),
	('Girafe', 'Giraffa camelopardalis', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'VU', 'Decreasing', 'Le plus grand animal terrestre, reconnaissable à son long cou et ses taches uniques.', 'https://source.unsplash.com/800x600/?girafe,wildlife'),
	('Zèbre des plaines', 'Equus quagga', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'NT', 'Decreasing', 'Équidé rayé vivant en troupeaux, chaque motif de rayures étant unique à l''individu.', 'https://source.unsplash.com/800x600/?z%C3%A8bre%20des%20plaines,wildlife'),
	('Gnou bleu', 'Connochaetes taurinus', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'LC', 'Stable', 'Antilope migratrice connue pour ses déplacements massifs annuels dans le Serengeti.', 'https://source.unsplash.com/800x600/?gnou%20bleu,wildlife'),
	('Buffle d''Afrique', 'Syncerus caffer', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'NT', 'Decreasing', 'Grand bovidé vivant en troupeaux, réputé pour son caractère imprévisible face aux prédateurs.', 'https://source.unsplash.com/800x600/?buffle%20dafrique,wildlife'),
	('Hippopotame', 'Hippopotamus amphibius', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'VU', 'Decreasing', 'Grand mammifère semi-aquatique passant la journée immergé dans les rivières africaines.', 'https://source.unsplash.com/800x600/?hippopotame,wildlife'),
	('Rhinocéros blanc', 'Ceratotherium simum', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'NT', 'Increasing', 'Deuxième plus grand mammifère terrestre, brouteur d''herbe menacé par le braconnage.', 'https://source.unsplash.com/800x600/?rhinoc%C3%A9ros%20blanc,wildlife'),
	('Rhinocéros noir', 'Diceros bicornis', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'CR', 'Increasing', 'Espèce en danger critique menacée par le braconnage pour ses cornes.', 'https://source.unsplash.com/800x600/?rhinoc%C3%A9ros%20noir,wildlife'),
	('Hyène tachetée', 'Crocuta crocuta', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Prédateur et charognard social vivant en clans matriarcaux complexes.', 'https://source.unsplash.com/800x600/?hy%C3%A8ne%20tachet%C3%A9e,wildlife'),
	('Lycaon', 'Lycaon pictus', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Carnivore', 'EN', 'Decreasing', 'Canidé social à la robe tachetée, chasseur en meute très efficace.', 'https://source.unsplash.com/800x600/?lycaon,wildlife'),
	('Impala', 'Aepyceros melampus', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'LC', 'Stable', 'Antilope agile capable de bonds spectaculaires pour échapper aux prédateurs.', 'https://source.unsplash.com/800x600/?impala,wildlife'),
	('Gazelle de Thomson', 'Eudorcas thomsonii', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'NT', 'Decreasing', 'Petite antilope rapide vivant en troupeaux dans les plaines d''Afrique de l''Est.', 'https://source.unsplash.com/800x600/?gazelle%20de%20thomson,wildlife'),
	('Gazelle de Grant', 'Nanger granti', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'LC', 'Stable', 'Antilope de taille moyenne capable de se passer d''eau pendant de longues périodes.', 'https://source.unsplash.com/800x600/?gazelle%20de%20grant,wildlife'),
	('Phacochère', 'Phacochoerus africanus', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Omnivore', 'LC', 'Stable', 'Suidé reconnaissable à ses défenses recourbées, se déplaçant souvent à genoux pour brouter.', 'https://source.unsplash.com/800x600/?phacoch%C3%A8re,wildlife'),
	('Éland du Cap', 'Taurotragus oryx', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'LC', 'Stable', 'La plus grande antilope au monde, capable de sauter plus de deux mètres.', 'https://source.unsplash.com/800x600/?%C3%A9land%20du%20cap,wildlife'),
	('Grand koudou', 'Tragelaphus strepsiceros', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'LC', 'Stable', 'Antilope aux cornes spiralées spectaculaires, très discrète dans les broussailles.', 'https://source.unsplash.com/800x600/?grand%20koudou,wildlife'),
	('Serval', 'Leptailurus serval', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Petit félin aux longues pattes, spécialiste de la chasse aux rongeurs par bonds.', 'https://source.unsplash.com/800x600/?serval,wildlife'),
	('Caracal', 'Caracal caracal', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Félin agile aux oreilles pointues touffues, capable de capturer des oiseaux en vol.', 'https://source.unsplash.com/800x600/?caracal,wildlife'),
	('Oryctérope', 'Orycteropus afer', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Omnivore', 'LC', 'Stable', 'Mammifère fouisseur nocturne se nourrissant presque exclusivement de fourmis et termites.', 'https://source.unsplash.com/800x600/?oryct%C3%A9rope,wildlife'),
	('Protèle', 'Proteles cristata', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Omnivore', 'LC', 'Stable', 'Petit charognard apparenté à la hyène, se nourrissant surtout de termites.', 'https://source.unsplash.com/800x600/?prot%C3%A8le,wildlife'),
	('Otocyon', 'Otocyon megalotis', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Omnivore', 'LC', 'Stable', 'Petit canidé aux grandes oreilles, principalement insectivore.', 'https://source.unsplash.com/800x600/?otocyon,wildlife'),
	('Suricate', 'Suricata suricatta', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Omnivore', 'LC', 'Stable', 'Petit mangouste vivant en groupes organisés avec des sentinelles de garde.', 'https://source.unsplash.com/800x600/?suricate,wildlife'),
	('Topi', 'Damaliscus lunatus', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'LC', 'Decreasing', 'Antilope robuste connue pour sa vitesse et son endurance sur de longues distances.', 'https://source.unsplash.com/800x600/?topi,wildlife'),
	('Cobe à croissant', 'Kobus ellipsiprymnus', 'Animalia', 'Chordata', 'Mammalia', 'Savane', 'Herbivore', 'LC', 'Stable', 'Grande antilope liée aux points d''eau, à la fourrure grasse et odorante.', 'https://source.unsplash.com/800x600/?cobe%20%C3%A0%20croissant,wildlife'),
	('Autruche d''Afrique', 'Struthio camelus', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Omnivore', 'LC', 'Stable', 'Le plus grand oiseau vivant, incapable de voler mais excellent coureur.', 'https://source.unsplash.com/800x600/?autruche%20dafrique,wildlife'),
	('Secrétaire', 'Sagittarius serpentarius', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Carnivore', 'EN', 'Decreasing', 'Rapace terrestre aux longues pattes, spécialiste de la chasse aux serpents.', 'https://source.unsplash.com/800x600/?secr%C3%A9taire,wildlife'),
	('Marabout d''Afrique', 'Leptoptilos crumenifer', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Omnivore', 'LC', 'Stable', 'Grand échassier charognard reconnaissable à sa tête chauve et son bec massif.', 'https://source.unsplash.com/800x600/?marabout%20dafrique,wildlife'),
	('Rollier à longs brins', 'Coracias caudatus', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Carnivore', 'LC', 'Stable', 'Oiseau aux couleurs vives connu pour ses vols acrobatiques nuptiaux.', 'https://source.unsplash.com/800x600/?rollier%20%C3%A0%20longs%20brins,wildlife'),
	('Bucorve du Sud', 'Bucorvus leadbeateri', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Carnivore', 'VU', 'Decreasing', 'Grand calao terrestre à la gorge rouge, chasseur de petits animaux au sol.', 'https://source.unsplash.com/800x600/?bucorve%20du%20sud,wildlife'),
	('Outarde kori', 'Ardeotis kori', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Omnivore', 'NT', 'Decreasing', 'Un des oiseaux volants les plus lourds, passant la majorité de son temps au sol.', 'https://source.unsplash.com/800x600/?outarde%20kori,wildlife'),
	('Vautour à dos blanc', 'Gyps africanus', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Carnivore', 'CR', 'Decreasing', 'Charognard essentiel à l''écosystème, en déclin critique à cause de l''empoisonnement.', 'https://source.unsplash.com/800x600/?vautour%20%C3%A0%20dos%20blanc,wildlife'),
	('Vautour à tête blanche', 'Trigonoceps occipitalis', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Carnivore', 'CR', 'Decreasing', 'Grand vautour solitaire menacé par la perte d''habitat et l''empoisonnement.', 'https://source.unsplash.com/800x600/?vautour%20%C3%A0%20t%C3%AAte%20blanche,wildlife'),
	('Pintade de Numidie', 'Numida meleagris', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Omnivore', 'LC', 'Stable', 'Oiseau grégaire au plumage tacheté, très commun dans les savanes africaines.', 'https://source.unsplash.com/800x600/?pintade%20de%20numidie,wildlife'),
	('Grue royale', 'Balearica regulorum', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Omnivore', 'EN', 'Decreasing', 'Grue élégante à la couronne de plumes dorées, emblème de l''Ouganda.', 'https://source.unsplash.com/800x600/?grue%20royale,wildlife'),
	('Choucador superbe', 'Lamprotornis superbus', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Omnivore', 'LC', 'Stable', 'Petit passereau aux plumes irisées bleu et vert vif, très commun en Afrique de l''Est.', 'https://source.unsplash.com/800x600/?choucador%20superbe,wildlife'),
	('Travailleur à bec rouge', 'Quelea quelea', 'Animalia', 'Chordata', 'Aves', 'Savane', 'Herbivore', 'LC', 'Stable', 'Petit oiseau grégaire formant les plus grandes volées d''oiseaux au monde.', 'https://source.unsplash.com/800x600/?travailleur%20%C3%A0%20bec%20rouge,wildlife'),
	('Crocodile du Nil', 'Crocodylus niloticus', 'Animalia', 'Chordata', 'Reptilia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Grand reptile prédateur des rivières et points d''eau africains.', 'https://source.unsplash.com/800x600/?crocodile%20du%20nil,wildlife'),
	('Python de Seba', 'Python sebae', 'Animalia', 'Chordata', 'Reptilia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Un des plus grands serpents d''Afrique, constricteur puissant.', 'https://source.unsplash.com/800x600/?python%20de%20seba,wildlife'),
	('Mamba noir', 'Dendroaspis polylepis', 'Animalia', 'Chordata', 'Reptilia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Serpent venimeux rapide et redouté, parmi les plus dangereux d''Afrique.', 'https://source.unsplash.com/800x600/?mamba%20noir,wildlife'),
	('Tortue léopard', 'Stigmochelys pardalis', 'Animalia', 'Chordata', 'Reptilia', 'Savane', 'Herbivore', 'LC', 'Decreasing', 'Grande tortue terrestre au carapace tachetée, herbivore des savanes sèches.', 'https://source.unsplash.com/800x600/?tortue%20l%C3%A9opard,wildlife'),
	('Varan du Nil', 'Varanus niloticus', 'Animalia', 'Chordata', 'Reptilia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Grand lézard semi-aquatique, prédateur opportuniste des berges africaines.', 'https://source.unsplash.com/800x600/?varan%20du%20nil,wildlife'),
	('Vipère heurtante', 'Bitis arietans', 'Animalia', 'Chordata', 'Reptilia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Serpent venimeux trapu, responsable de nombreuses morsures en Afrique.', 'https://source.unsplash.com/800x600/?vip%C3%A8re%20heurtante,wildlife'),
	('Boomslang', 'Dispholidus typus', 'Animalia', 'Chordata', 'Reptilia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Serpent arboricole venimeux aux grands yeux, discret dans les acacias.', 'https://source.unsplash.com/800x600/?boomslang,wildlife'),
	('Tortue à éperons', 'Centrochelys sulcata', 'Animalia', 'Chordata', 'Reptilia', 'Savane', 'Herbivore', 'EN', 'Decreasing', 'Troisième plus grande tortue terrestre au monde, adaptée aux zones arides.', 'https://source.unsplash.com/800x600/?tortue%20%C3%A0%20%C3%A9perons,wildlife'),
	('Grenouille taureau africaine', 'Pyxicephalus adspersus', 'Animalia', 'Chordata', 'Amphibia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Grande grenouille robuste et vorace, capable d''avaler de petits vertébrés.', 'https://source.unsplash.com/800x600/?grenouille%20taureau%20africaine,wildlife'),
	('Rainette peinte', 'Hyperolius marmoratus', 'Animalia', 'Chordata', 'Amphibia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Petite rainette aux motifs variables, très commune près des points d''eau.', 'https://source.unsplash.com/800x600/?rainette%20peinte,wildlife'),
	('Crapaud guttural', 'Sclerophrys gutturalis', 'Animalia', 'Chordata', 'Amphibia', 'Savane', 'Carnivore', 'LC', 'Stable', 'Crapaud robuste et adaptable, fréquent autour des habitations africaines.', 'https://source.unsplash.com/800x600/?crapaud%20guttural,wildlife'),
	('Jaguar', 'Panthera onca', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Carnivore', 'NT', 'Decreasing', 'Le plus grand félin d''Amérique, excellent nageur chassant caïmans et capybaras.', 'https://source.unsplash.com/800x600/?jaguar,wildlife'),
	('Tigre de Sumatra', 'Panthera tigris sumatrae', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Carnivore', 'CR', 'Decreasing', 'Sous-espèce de tigre la plus petite, menacée par la déforestation de Sumatra.', 'https://source.unsplash.com/800x600/?tigre%20de%20sumatra,wildlife'),
	('Gorille des plaines de l''Ouest', 'Gorilla gorilla gorilla', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Herbivore', 'CR', 'Decreasing', 'Grand primate vivant en groupes familiaux dans les forêts d''Afrique centrale.', 'https://source.unsplash.com/800x600/?gorille%20des%20plaines%20de%20louest,wildlife'),
	('Chimpanzé', 'Pan troglodytes', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Omnivore', 'EN', 'Decreasing', 'Grand singe très social, un de nos plus proches parents génétiques.', 'https://source.unsplash.com/800x600/?chimpanz%C3%A9,wildlife'),
	('Bonobo', 'Pan paniscus', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Omnivore', 'EN', 'Decreasing', 'Grand singe à la société matriarcale pacifique, endémique du Congo.', 'https://source.unsplash.com/800x600/?bonobo,wildlife'),
	('Orang-outan de Bornéo', 'Pongo pygmaeus', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Omnivore', 'CR', 'Decreasing', 'Grand singe arboricole d''Asie du Sud-Est menacé par la déforestation.', 'https://source.unsplash.com/800x600/?orang-outan%20de%20born%C3%A9o,wildlife'),
	('Loutre géante', 'Pteronura brasiliensis', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Carnivore', 'EN', 'Decreasing', 'Plus grande loutre du monde, vivant en groupes familiaux le long des rivières amazoniennes.', 'https://source.unsplash.com/800x600/?loutre%20g%C3%A9ante,wildlife'),
	('Ocelot', 'Leopardus pardalis', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Carnivore', 'LC', 'Decreasing', 'Petit félin tacheté nocturne, excellent chasseur au sol comme dans les arbres.', 'https://source.unsplash.com/800x600/?ocelot,wildlife'),
	('Tapir terrestre', 'Tapirus terrestris', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Herbivore', 'VU', 'Decreasing', 'Grand mammifère au museau préhensile, disperseur essentiel de graines en Amazonie.', 'https://source.unsplash.com/800x600/?tapir%20terrestre,wildlife'),
	('Paresseux à gorge brune', 'Bradypus variegatus', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Herbivore', 'LC', 'Stable', 'Mammifère arboricole au métabolisme très lent, passant sa vie dans la canopée.', 'https://source.unsplash.com/800x600/?paresseux%20%C3%A0%20gorge%20brune,wildlife'),
	('Tamarin lion doré', 'Leontopithecus rosalia', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Omnivore', 'EN', 'Increasing', 'Petit primate au pelage doré éclatant, sauvé de justesse grâce à la conservation.', 'https://source.unsplash.com/800x600/?tamarin%20lion%20dor%C3%A9,wildlife'),
	('Fourmilier géant', 'Myrmecophaga tridactyla', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tropicale', 'Carnivore', 'VU', 'Decreasing', 'Grand mammifère à la longue langue, se nourrissant de fourmis et termites.', 'https://source.unsplash.com/800x600/?fourmilier%20g%C3%A9ant,wildlife'),
	('Ara macao', 'Ara macao', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'LC', 'Decreasing', 'Grand perroquet rouge, jaune et bleu emblématique des forêts d''Amérique centrale.', 'https://source.unsplash.com/800x600/?ara%20macao,wildlife'),
	('Ara bleu et jaune', 'Ara ararauna', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'LC', 'Decreasing', 'Grand perroquet coloré vivant en couples fidèles à vie.', 'https://source.unsplash.com/800x600/?ara%20bleu%20et%20jaune,wildlife'),
	('Toucan toco', 'Ramphastos toco', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'LC', 'Stable', 'Le plus grand toucan, reconnaissable à son bec orange démesuré.', 'https://source.unsplash.com/800x600/?toucan%20toco,wildlife'),
	('Toucan à carène', 'Ramphastos sulfuratus', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'NT', 'Decreasing', 'Toucan aux couleurs vives, vivant en petits groupes dans la canopée.', 'https://source.unsplash.com/800x600/?toucan%20%C3%A0%20car%C3%A8ne,wildlife'),
	('Harpie féroce', 'Harpia harpyja', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Carnivore', 'NT', 'Decreasing', 'Un des plus puissants rapaces au monde, chasseur de singes et de paresseux.', 'https://source.unsplash.com/800x600/?harpie%20f%C3%A9roce,wildlife'),
	('Quetzal resplendissant', 'Pharomachrus mocinno', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'NT', 'Decreasing', 'Oiseau sacré des Mayas aux longues plumes caudales irisées vert émeraude.', 'https://source.unsplash.com/800x600/?quetzal%20resplendissant,wildlife'),
	('Ara hyacinthe', 'Anodorhynchus hyacinthinus', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Herbivore', 'VU', 'Decreasing', 'Le plus grand perroquet volant au monde, au plumage bleu cobalt.', 'https://source.unsplash.com/800x600/?ara%20hyacinthe,wildlife'),
	('Calao rhinocéros', 'Buceros rhinoceros', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'VU', 'Decreasing', 'Grand calao asiatique au casque proéminent en forme de corne.', 'https://source.unsplash.com/800x600/?calao%20rhinoc%C3%A9ros,wildlife'),
	('Calao bicorne', 'Buceros bicornis', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'VU', 'Decreasing', 'Un des plus grands calaos, symbole culturel important en Asie du Sud.', 'https://source.unsplash.com/800x600/?calao%20bicorne,wildlife'),
	('Paradisier du roi', 'Cicinnurus regius', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'LC', 'Stable', 'Petit oiseau de paradis au plumage rouge vif et parades spectaculaires.', 'https://source.unsplash.com/800x600/?paradisier%20du%20roi,wildlife'),
	('Paradisier de Wilson', 'Cicinnurus respublica', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'NT', 'Decreasing', 'Oiseau de paradis aux couleurs extravagantes, endémique de Nouvelle-Guinée occidentale.', 'https://source.unsplash.com/800x600/?paradisier%20de%20wilson,wildlife'),
	('Coq-de-roche orange', 'Rupicola rupicola', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'LC', 'Stable', 'Oiseau au plumage orange vif, célèbre pour ses parades collectives spectaculaires.', 'https://source.unsplash.com/800x600/?coq-de-roche%20orange,wildlife'),
	('Paon spicifère', 'Pavo muticus', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'EN', 'Decreasing', 'Grand paon asiatique au plumage vert métallique, menacé par la chasse.', 'https://source.unsplash.com/800x600/?paon%20spicif%C3%A8re,wildlife'),
	('Cacatoès de Goffin', 'Cacatua goffiniana', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'NT', 'Decreasing', 'Petit cacatoès blanc réputé pour son intelligence et sa capacité à utiliser des outils.', 'https://source.unsplash.com/800x600/?cacato%C3%A8s%20de%20goffin,wildlife'),
	('Hoazin huppé', 'Opisthocomus hoazin', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Herbivore', 'LC', 'Stable', 'Oiseau unique digérant les feuilles par fermentation, dégageant une odeur particulière.', 'https://source.unsplash.com/800x600/?hoazin%20hupp%C3%A9,wildlife'),
	('Martin-pêcheur d''Amazonie', 'Chloroceryle amazona', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Petit martin-pêcheur pêchant le long des rivières et cours d''eau amazoniens.', 'https://source.unsplash.com/800x600/?martin-p%C3%AAcheur%20damazonie,wildlife'),
	('Motmot houtouc', 'Momotus momota', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Omnivore', 'LC', 'Stable', 'Oiseau coloré à la queue en forme de raquette, discret dans le sous-bois.', 'https://source.unsplash.com/800x600/?motmot%20houtouc,wildlife'),
	('Loriquet à tête bleue', 'Trichoglossus haematodus', 'Animalia', 'Chordata', 'Aves', 'Forêt tropicale', 'Herbivore', 'LC', 'Stable', 'Petit perroquet coloré se nourrissant principalement de nectar et de pollen.', 'https://source.unsplash.com/800x600/?loriquet%20%C3%A0%20t%C3%AAte%20bleue,wildlife'),
	('Anaconda vert', 'Eunectes murinus', 'Animalia', 'Chordata', 'Reptilia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Un des plus grands et plus lourds serpents au monde, excellent nageur.', 'https://source.unsplash.com/800x600/?anaconda%20vert,wildlife'),
	('Cobra royal', 'Ophiophagus hannah', 'Animalia', 'Chordata', 'Reptilia', 'Forêt tropicale', 'Carnivore', 'VU', 'Decreasing', 'Le plus long serpent venimeux au monde, se nourrissant principalement d''autres serpents.', 'https://source.unsplash.com/800x600/?cobra%20royal,wildlife'),
	('Python réticulé', 'Malayopython reticulatus', 'Animalia', 'Chordata', 'Reptilia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Le plus long serpent du monde, constricteur redoutable d''Asie du Sud-Est.', 'https://source.unsplash.com/800x600/?python%20r%C3%A9ticul%C3%A9,wildlife'),
	('Boa émeraude', 'Corallus caninus', 'Animalia', 'Chordata', 'Reptilia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Serpent arboricole vert vif, chassant la nuit perché dans les branches.', 'https://source.unsplash.com/800x600/?boa%20%C3%A9meraude,wildlife'),
	('Dragon de Komodo', 'Varanus komodoensis', 'Animalia', 'Chordata', 'Reptilia', 'Forêt tropicale', 'Carnivore', 'EN', 'Decreasing', 'Le plus grand lézard vivant, prédateur apex de ses îles indonésiennes.', 'https://source.unsplash.com/800x600/?dragon%20de%20komodo,wildlife'),
	('Caméléon panthère', 'Furcifer pardalis', 'Animalia', 'Chordata', 'Reptilia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Caméléon aux couleurs vives changeantes, endémique de Madagascar.', 'https://source.unsplash.com/800x600/?cam%C3%A9l%C3%A9on%20panth%C3%A8re,wildlife'),
	('Vipère à cils', 'Bothriechis schlegelii', 'Animalia', 'Chordata', 'Reptilia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Petite vipère arboricole aux écailles sourcilières distinctives, très variable en couleur.', 'https://source.unsplash.com/800x600/?vip%C3%A8re%20%C3%A0%20cils,wildlife'),
	('Dendrobate azuréen', 'Dendrobates tinctorius azureus', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Petite grenouille toxique au bleu éclatant, avertissant les prédateurs de sa toxicité.', 'https://source.unsplash.com/800x600/?dendrobate%20azur%C3%A9en,wildlife'),
	('Grenouille fraise', 'Oophaga pumilio', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Petite grenouille venimeuse rouge vif, transportant ses têtards sur son dos.', 'https://source.unsplash.com/800x600/?grenouille%20fraise,wildlife'),
	('Rainette aux yeux rouges', 'Agalychnis callidryas', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Rainette emblématique d''Amérique centrale aux yeux rouges vifs et flancs bleus.', 'https://source.unsplash.com/800x600/?rainette%20aux%20yeux%20rouges,wildlife'),
	('Grenouille dorée toxique', 'Phyllobates terribilis', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tropicale', 'Carnivore', 'EN', 'Decreasing', 'La grenouille la plus toxique au monde, utilisée traditionnellement pour empoisonner des sarbacanes.', 'https://source.unsplash.com/800x600/?grenouille%20dor%C3%A9e%20toxique,wildlife'),
	('Rainette laiteuse d''Amazonie', 'Trachycephalus resinifictrix', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Grande rainette au motif marbré, sécrétant une substance laiteuse défensive.', 'https://source.unsplash.com/800x600/?rainette%20laiteuse%20damazonie,wildlife'),
	('Pipa du Suriname', 'Pipa pipa', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Grenouille aquatique aplatie incubant ses œufs dans des alvéoles sur son dos.', 'https://source.unsplash.com/800x600/?pipa%20du%20suriname,wildlife'),
	('Rainette cireuse', 'Phyllomedusa sauvagii', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Rainette sécrétant une cire cutanée pour limiter la déshydratation.', 'https://source.unsplash.com/800x600/?rainette%20cireuse,wildlife'),
	('Grenouille cornue de Malaisie', 'Megophrys nasuta', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tropicale', 'Carnivore', 'LC', 'Decreasing', 'Grenouille au camouflage exceptionnel imitant une feuille morte.', 'https://source.unsplash.com/800x600/?grenouille%20cornue%20de%20malaisie,wildlife'),
	('Grenouille mousse du Vietnam', 'Theloderma corticale', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Petite grenouille au camouflage remarquable imitant la mousse et le lichen.', 'https://source.unsplash.com/800x600/?grenouille%20mousse%20du%20vietnam,wildlife'),
	('Grenouille goliath', 'Conraua goliath', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tropicale', 'Carnivore', 'EN', 'Decreasing', 'La plus grande grenouille au monde, pouvant peser plus de trois kilogrammes.', 'https://source.unsplash.com/800x600/?grenouille%20goliath,wildlife'),
	('Piranha à ventre rouge', 'Pygocentrus nattereri', 'Animalia', 'Chordata', 'Pisces', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Poisson grégaire aux dents acérées, souvent réputé plus dangereux qu''il ne l''est réellement.', 'https://source.unsplash.com/800x600/?piranha%20%C3%A0%20ventre%20rouge,wildlife'),
	('Arapaïma', 'Arapaima gigas', 'Animalia', 'Chordata', 'Pisces', 'Forêt tropicale', 'Carnivore', 'VU', 'Decreasing', 'Un des plus grands poissons d''eau douce, respirant l''air atmosphérique en surface.', 'https://source.unsplash.com/800x600/?arapa%C3%AFma,wildlife'),
	('Anguille électrique', 'Electrophorus electricus', 'Animalia', 'Chordata', 'Pisces', 'Forêt tropicale', 'Carnivore', 'LC', 'Stable', 'Poisson capable de générer des décharges électriques puissantes pour chasser et se défendre.', 'https://source.unsplash.com/800x600/?anguille%20%C3%A9lectrique,wildlife'),
	('Baleine bleue', 'Balaenoptera musculus', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'EN', 'Stable', 'Le plus grand animal ayant jamais existé, se nourrissant de krill par filtration.', 'https://source.unsplash.com/800x600/?baleine%20bleue,wildlife'),
	('Baleine à bosse', 'Megaptera novaeangliae', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'LC', 'Increasing', 'Grand cétacé migrateur célèbre pour ses chants complexes et ses sauts spectaculaires.', 'https://source.unsplash.com/800x600/?baleine%20%C3%A0%20bosse,wildlife'),
	('Orque', 'Orcinus orca', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'NT', 'Decreasing', 'Le plus grand dauphin, prédateur apex chassant en groupes familiaux coordonnés.', 'https://source.unsplash.com/800x600/?orque,wildlife'),
	('Cachalot', 'Physeter macrocephalus', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'VU', 'Decreasing', 'Le plus grand des odontocètes, plongeant à grande profondeur pour chasser le calmar géant.', 'https://source.unsplash.com/800x600/?cachalot,wildlife'),
	('Grand dauphin', 'Tursiops truncatus', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'LC', 'Stable', 'Dauphin intelligent et sociable, l''un des cétacés les plus étudiés au monde.', 'https://source.unsplash.com/800x600/?grand%20dauphin,wildlife'),
	('Narval', 'Monodon monoceros', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'LC', 'Stable', 'Cétacé arctique dont le mâle porte une longue défense torsadée unique.', 'https://source.unsplash.com/800x600/?narval,wildlife'),
	('Béluga', 'Delphinapterus leucas', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'LC', 'Decreasing', 'Cétacé blanc arctique très vocal, surnommé le canari des mers.', 'https://source.unsplash.com/800x600/?b%C3%A9luga,wildlife'),
	('Phoque commun', 'Phoca vitulina', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'LC', 'Stable', 'Petit pinnipède côtier commun dans l''hémisphère nord.', 'https://source.unsplash.com/800x600/?phoque%20commun,wildlife'),
	('Éléphant de mer austral', 'Mirounga leonina', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'LC', 'Stable', 'Plus grand pinnipède au monde, plongeant à des profondeurs extrêmes pour se nourrir.', 'https://source.unsplash.com/800x600/?%C3%A9l%C3%A9phant%20de%20mer%20austral,wildlife'),
	('Morse', 'Odobenus rosmarus', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'VU', 'Decreasing', 'Grand pinnipède arctique aux longues défenses, dépendant de la banquise.', 'https://source.unsplash.com/800x600/?morse,wildlife'),
	('Lamantin des Caraïbes', 'Trichechus manatus', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Herbivore', 'VU', 'Decreasing', 'Mammifère marin paisible se nourrissant d''herbiers marins dans les eaux côtières chaudes.', 'https://source.unsplash.com/800x600/?lamantin%20des%20cara%C3%AFbes,wildlife'),
	('Dugong', 'Dugong dugon', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Herbivore', 'VU', 'Decreasing', 'Sirénien marin brouteur d''herbiers, proche parent du lamantin.', 'https://source.unsplash.com/800x600/?dugong,wildlife'),
	('Léopard de mer', 'Hydrurga leptonyx', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'LC', 'Stable', 'Grand phoque antarctique prédateur redoutable des manchots et autres phoques.', 'https://source.unsplash.com/800x600/?l%C3%A9opard%20de%20mer,wildlife'),
	('Rorqual commun', 'Balaenoptera physalus', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'VU', 'Increasing', 'Deuxième plus grand animal au monde après la baleine bleue.', 'https://source.unsplash.com/800x600/?rorqual%20commun,wildlife'),
	('Baleine grise', 'Eschrichtius robustus', 'Animalia', 'Chordata', 'Mammalia', 'Océan', 'Carnivore', 'LC', 'Increasing', 'Cétacé migrateur effectuant l''une des plus longues migrations parmi les mammifères.', 'https://source.unsplash.com/800x600/?baleine%20grise,wildlife'),
	('Albatros hurleur', 'Diomedea exulans', 'Animalia', 'Chordata', 'Aves', 'Océan', 'Carnivore', 'VU', 'Decreasing', 'Oiseau à la plus grande envergure alaire au monde, planant sur des milliers de kilomètres.', 'https://source.unsplash.com/800x600/?albatros%20hurleur,wildlife'),
	('Macareux moine', 'Fratercula arctica', 'Animalia', 'Chordata', 'Aves', 'Océan', 'Carnivore', 'VU', 'Decreasing', 'Petit oiseau marin au bec coloré, nichant en colonies sur les falaises côtières.', 'https://source.unsplash.com/800x600/?macareux%20moine,wildlife'),
	('Manchot empereur', 'Aptenodytes forsteri', 'Animalia', 'Chordata', 'Aves', 'Océan', 'Carnivore', 'NT', 'Decreasing', 'Le plus grand des manchots, se reproduisant durant l''hiver antarctique extrême.', 'https://source.unsplash.com/800x600/?manchot%20empereur,wildlife'),
	('Manchot royal', 'Aptenodytes patagonicus', 'Animalia', 'Chordata', 'Aves', 'Océan', 'Carnivore', 'LC', 'Increasing', 'Deuxième plus grand manchot, vivant en immenses colonies subantarctiques.', 'https://source.unsplash.com/800x600/?manchot%20royal,wildlife'),
	('Fou de Bassan', 'Morus bassanus', 'Animalia', 'Chordata', 'Aves', 'Océan', 'Carnivore', 'LC', 'Increasing', 'Grand oiseau marin plongeant en piqué spectaculaire pour capturer des poissons.', 'https://source.unsplash.com/800x600/?fou%20de%20bassan,wildlife'),
	('Frégate superbe', 'Fregata magnificens', 'Animalia', 'Chordata', 'Aves', 'Océan', 'Carnivore', 'LC', 'Stable', 'Oiseau marin au mâle arborant un sac gulaire rouge gonflable pour la parade.', 'https://source.unsplash.com/800x600/?fr%C3%A9gate%20superbe,wildlife'),
	('Pélican brun', 'Pelecanus occidentalis', 'Animalia', 'Chordata', 'Aves', 'Océan', 'Carnivore', 'LC', 'Increasing', 'Pélican plongeur capturant ses proies en piquant depuis les airs.', 'https://source.unsplash.com/800x600/?p%C3%A9lican%20brun,wildlife'),
	('Sterne arctique', 'Sterna paradisaea', 'Animalia', 'Chordata', 'Aves', 'Océan', 'Carnivore', 'LC', 'Stable', 'Oiseau migrateur effectuant le plus long trajet migratoire connu, du pôle Nord au pôle Sud.', 'https://source.unsplash.com/800x600/?sterne%20arctique,wildlife'),
	('Tortue verte', 'Chelonia mydas', 'Animalia', 'Chordata', 'Reptilia', 'Océan', 'Herbivore', 'EN', 'Decreasing', 'Grande tortue marine herbivore, parcourant de longues distances entre zones d''alimentation et de ponte.', 'https://source.unsplash.com/800x600/?tortue%20verte,wildlife'),
	('Tortue caouanne', 'Caretta caretta', 'Animalia', 'Chordata', 'Reptilia', 'Océan', 'Carnivore', 'VU', 'Decreasing', 'Tortue marine à la grosse tête, se nourrissant principalement de mollusques et crustacés.', 'https://source.unsplash.com/800x600/?tortue%20caouanne,wildlife'),
	('Tortue luth', 'Dermochelys coriacea', 'Animalia', 'Chordata', 'Reptilia', 'Océan', 'Carnivore', 'VU', 'Decreasing', 'Plus grande tortue marine au monde, dépourvue de carapace osseuse rigide.', 'https://source.unsplash.com/800x600/?tortue%20luth,wildlife'),
	('Grand requin blanc', 'Carcharodon carcharias', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Carnivore', 'VU', 'Decreasing', 'Prédateur marin apex, le plus grand poisson prédateur au monde.', 'https://source.unsplash.com/800x600/?grand%20requin%20blanc,wildlife'),
	('Requin-baleine', 'Rhincodon typus', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Omnivore', 'EN', 'Decreasing', 'Le plus grand poisson au monde, filtreur paisible de plancton.', 'https://source.unsplash.com/800x600/?requin-baleine,wildlife'),
	('Requin-marteau halicorne', 'Sphyrna lewini', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Carnivore', 'CR', 'Decreasing', 'Requin à la tête en forme de marteau, très menacé par la pêche aux ailerons.', 'https://source.unsplash.com/800x600/?requin-marteau%20halicorne,wildlife'),
	('Raie manta géante', 'Mobula birostris', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Omnivore', 'EN', 'Decreasing', 'Le plus grand des raies, filtreur de plancton aux nageoires pectorales immenses.', 'https://source.unsplash.com/800x600/?raie%20manta%20g%C3%A9ante,wildlife'),
	('Poisson-clown ocellé', 'Amphiprion ocellaris', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Omnivore', 'LC', 'Stable', 'Petit poisson corallien vivant en symbiose avec les anémones de mer.', 'https://source.unsplash.com/800x600/?poisson-clown%20ocell%C3%A9,wildlife'),
	('Thon rouge de l''Atlantique', 'Thunnus thynnus', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Carnivore', 'EN', 'Increasing', 'Grand poisson pélagique très prisé, surexploité par la pêche commerciale.', 'https://source.unsplash.com/800x600/?thon%20rouge%20de%20latlantique,wildlife'),
	('Espadon', 'Xiphias gladius', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Carnivore', 'LC', 'Stable', 'Poisson pélagique rapide au long rostre plat utilisé pour étourdir ses proies.', 'https://source.unsplash.com/800x600/?espadon,wildlife'),
	('Morue de l''Atlantique', 'Gadus morhua', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Carnivore', 'VU', 'Decreasing', 'Poisson historique de la pêche commerciale, dont les stocks se sont effondrés.', 'https://source.unsplash.com/800x600/?morue%20de%20latlantique,wildlife'),
	('Poisson-lune', 'Mola mola', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Omnivore', 'VU', 'Decreasing', 'Le plus lourd poisson osseux au monde, à la silhouette tronquée caractéristique.', 'https://source.unsplash.com/800x600/?poisson-lune,wildlife'),
	('Marlin bleu', 'Makaira nigricans', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Carnivore', 'VU', 'Decreasing', 'Grand poisson pélagique rapide très recherché par la pêche sportive.', 'https://source.unsplash.com/800x600/?marlin%20bleu,wildlife'),
	('Poisson-lion rouge', 'Pterois volitans', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Carnivore', 'LC', 'Increasing', 'Poisson venimeux aux nageoires rayées, espèce invasive dans l''Atlantique.', 'https://source.unsplash.com/800x600/?poisson-lion%20rouge,wildlife'),
	('Napoléon', 'Cheilinus undulatus', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Carnivore', 'EN', 'Decreasing', 'Grand poisson corallien au front bombé, menacé par la pêche vivrière asiatique.', 'https://source.unsplash.com/800x600/?napol%C3%A9on,wildlife'),
	('Esturgeon beluga', 'Huso huso', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Carnivore', 'CR', 'Decreasing', 'Le plus grand esturgeon, gravement menacé par la surpêche pour son caviar.', 'https://source.unsplash.com/800x600/?esturgeon%20beluga,wildlife'),
	('Ours brun eurasien', 'Ursus arctos arctos', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Omnivore', 'LC', 'Stable', 'Grand plantigrade opportuniste des forêts d''Europe et d''Asie.', 'https://source.unsplash.com/800x600/?ours%20brun%20eurasien,wildlife'),
	('Ours noir d''Amérique', 'Ursus americanus', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Omnivore', 'LC', 'Increasing', 'Ours le plus commun d''Amérique du Nord, très adaptable.', 'https://source.unsplash.com/800x600/?ours%20noir%20dam%C3%A9rique,wildlife'),
	('Loup gris', 'Canis lupus', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Carnivore', 'LC', 'Stable', 'Canidé social chassant en meutes structurées, ancêtre du chien domestique.', 'https://source.unsplash.com/800x600/?loup%20gris,wildlife'),
	('Renard roux', 'Vulpes vulpes', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Omnivore', 'LC', 'Stable', 'Canidé opportuniste très répandu, capable de s''adapter à presque tous les habitats.', 'https://source.unsplash.com/800x600/?renard%20roux,wildlife'),
	('Lynx boréal', 'Lynx lynx', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Carnivore', 'LC', 'Stable', 'Félin discret aux pinceaux d''oreilles caractéristiques, chasseur de chevreuils.', 'https://source.unsplash.com/800x600/?lynx%20bor%C3%A9al,wildlife'),
	('Blaireau européen', 'Meles meles', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Omnivore', 'LC', 'Stable', 'Mustélidé fouisseur vivant en clans dans de vastes terriers appelés blaireautières.', 'https://source.unsplash.com/800x600/?blaireau%20europ%C3%A9en,wildlife'),
	('Cerf élaphe', 'Cervus elaphus', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Herbivore', 'LC', 'Stable', 'Grand cervidé dont le mâle porte des bois impressionnants renouvelés chaque année.', 'https://source.unsplash.com/800x600/?cerf%20%C3%A9laphe,wildlife'),
	('Cerf de Virginie', 'Odocoileus virginianus', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Herbivore', 'LC', 'Stable', 'Cervidé très répandu en Amérique du Nord, à la queue blanche caractéristique.', 'https://source.unsplash.com/800x600/?cerf%20de%20virginie,wildlife'),
	('Chevreuil européen', 'Capreolus capreolus', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Herbivore', 'LC', 'Stable', 'Petit cervidé discret des forêts et lisières européennes.', 'https://source.unsplash.com/800x600/?chevreuil%20europ%C3%A9en,wildlife'),
	('Sanglier', 'Sus scrofa', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Omnivore', 'LC', 'Increasing', 'Suidé robuste et opportuniste, ancêtre sauvage du porc domestique.', 'https://source.unsplash.com/800x600/?sanglier,wildlife'),
	('Raton laveur', 'Procyon lotor', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Omnivore', 'LC', 'Increasing', 'Petit carnivore nord-américain agile, reconnu pour son masque facial et sa dextérité.', 'https://source.unsplash.com/800x600/?raton%20laveur,wildlife'),
	('Pékan', 'Pekania pennanti', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Carnivore', 'LC', 'Stable', 'Mustélidé arboricole nord-américain, un des rares prédateurs du porc-épic.', 'https://source.unsplash.com/800x600/?p%C3%A9kan,wildlife'),
	('Castor du Canada', 'Castor canadensis', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Herbivore', 'LC', 'Stable', 'Grand rongeur ingénieur des cours d''eau, construisant barrages et huttes.', 'https://source.unsplash.com/800x600/?castor%20du%20canada,wildlife'),
	('Loutre d''Europe', 'Lutra lutra', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Carnivore', 'NT', 'Increasing', 'Mustélidé semi-aquatique piscivore des rivières européennes.', 'https://source.unsplash.com/800x600/?loutre%20deurope,wildlife'),
	('Martre des pins', 'Martes martes', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Omnivore', 'LC', 'Stable', 'Petit mustélidé arboricole discret, chasseur agile dans la canopée.', 'https://source.unsplash.com/800x600/?martre%20des%20pins,wildlife'),
	('Écureuil roux', 'Sciurus vulgaris', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Herbivore', 'LC', 'Decreasing', 'Petit rongeur arboricole emblématique des forêts européennes, en déclin face à l''écureuil gris.', 'https://source.unsplash.com/800x600/?%C3%A9cureuil%20roux,wildlife'),
	('Hérisson d''Europe', 'Erinaceus europaeus', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Omnivore', 'LC', 'Decreasing', 'Petit mammifère nocturne aux piquants défensifs, insectivore des jardins et forêts.', 'https://source.unsplash.com/800x600/?h%C3%A9risson%20deurope,wildlife'),
	('Élan', 'Alces alces', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Herbivore', 'LC', 'Stable', 'Plus grand cervidé au monde, aux larges bois palmés chez le mâle.', 'https://source.unsplash.com/800x600/?%C3%A9lan,wildlife'),
	('Porc-épic d''Amérique du Nord', 'Erethizon dorsatum', 'Animalia', 'Chordata', 'Mammalia', 'Forêt tempérée', 'Herbivore', 'LC', 'Stable', 'Rongeur arboricole recouvert de piquants défensifs redoutables.', 'https://source.unsplash.com/800x600/?porc-%C3%A9pic%20dam%C3%A9rique%20du%20nord,wildlife'),
	('Hibou grand-duc d''Europe', 'Bubo bubo', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Carnivore', 'LC', 'Stable', 'Un des plus grands hiboux au monde, prédateur nocturne redouté.', 'https://source.unsplash.com/800x600/?hibou%20grand-duc%20deurope,wildlife'),
	('Grand-duc d''Amérique', 'Bubo virginianus', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Carnivore', 'LC', 'Stable', 'Rapace nocturne puissant capable de chasser des proies plus grandes que lui.', 'https://source.unsplash.com/800x600/?grand-duc%20dam%C3%A9rique,wildlife'),
	('Pygargue à tête blanche', 'Haliaeetus leucocephalus', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Carnivore', 'LC', 'Increasing', 'Emblème national des États-Unis, grand rapace piscivore rétabli après le déclin du DDT.', 'https://source.unsplash.com/800x600/?pygargue%20%C3%A0%20t%C3%AAte%20blanche,wildlife'),
	('Faisan doré', 'Chrysolophus pictus', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Omnivore', 'LC', 'Stable', 'Faisan asiatique au plumage éclatant, introduit dans plusieurs pays occidentaux.', 'https://source.unsplash.com/800x600/?faisan%20dor%C3%A9,wildlife'),
	('Geai des chênes', 'Garrulus glandarius', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Omnivore', 'LC', 'Stable', 'Corvidé forestier disperseur important de glands de chêne.', 'https://source.unsplash.com/800x600/?geai%20des%20ch%C3%AAnes,wildlife'),
	('Rougegorge familier', 'Erithacus rubecula', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Omnivore', 'LC', 'Stable', 'Petit passereau européen à la gorge orangée, territorial et peu farouche.', 'https://source.unsplash.com/800x600/?rougegorge%20familier,wildlife'),
	('Pic épeiche', 'Dendrocopos major', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Omnivore', 'LC', 'Stable', 'Pic commun d''Europe, reconnaissable à son tambourinage rapide sur le bois.', 'https://source.unsplash.com/800x600/?pic%20%C3%A9peiche,wildlife'),
	('Grand pic', 'Dryocopus pileatus', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Omnivore', 'LC', 'Stable', 'Grand pic nord-américain à la huppe rouge flamboyante.', 'https://source.unsplash.com/800x600/?grand%20pic,wildlife'),
	('Pinson des arbres', 'Fringilla coelebs', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Herbivore', 'LC', 'Stable', 'Petit passereau très commun des forêts et jardins européens.', 'https://source.unsplash.com/800x600/?pinson%20des%20arbres,wildlife'),
	('Merle noir', 'Turdus merula', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Omnivore', 'LC', 'Stable', 'Passereau très répandu, reconnu pour son chant mélodieux au crépuscule.', 'https://source.unsplash.com/800x600/?merle%20noir,wildlife'),
	('Chouette effraie', 'Tyto alba', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Carnivore', 'LC', 'Stable', 'Rapace nocturne au visage en cœur, chasseur silencieux de petits rongeurs.', 'https://source.unsplash.com/800x600/?chouette%20effraie,wildlife'),
	('Faucon pèlerin', 'Falco peregrinus', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Carnivore', 'LC', 'Increasing', 'L''animal le plus rapide au monde en piqué, chassant d''autres oiseaux en vol.', 'https://source.unsplash.com/800x600/?faucon%20p%C3%A8lerin,wildlife'),
	('Dindon sauvage', 'Meleagris gallopavo', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Omnivore', 'LC', 'Increasing', 'Grand gallinacé nord-américain, ancêtre sauvage du dindon domestique.', 'https://source.unsplash.com/800x600/?dindon%20sauvage,wildlife'),
	('Geai bleu', 'Cyanocitta cristata', 'Animalia', 'Chordata', 'Aves', 'Forêt tempérée', 'Omnivore', 'LC', 'Stable', 'Corvidé nord-américain au plumage bleu vif, intelligent et bruyant.', 'https://source.unsplash.com/800x600/?geai%20bleu,wildlife'),
	('Couleuvre à collier', 'Natrix natrix', 'Animalia', 'Chordata', 'Reptilia', 'Forêt tempérée', 'Carnivore', 'LC', 'Decreasing', 'Couleuvre non venimeuse d''Europe, souvent trouvée près des points d''eau.', 'https://source.unsplash.com/800x600/?couleuvre%20%C3%A0%20collier,wildlife'),
	('Tortue à boîte de Caroline', 'Terrapene carolina', 'Animalia', 'Chordata', 'Reptilia', 'Forêt tempérée', 'Omnivore', 'VU', 'Decreasing', 'Petite tortue terrestre nord-américaine capable de refermer complètement sa carapace.', 'https://source.unsplash.com/800x600/?tortue%20%C3%A0%20bo%C3%AEte%20de%20caroline,wildlife'),
	('Salamandre tachetée', 'Salamandra salamandra', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tempérée', 'Carnivore', 'LC', 'Stable', 'Amphibien noir aux taches jaunes vives, signalant sa toxicité cutanée.', 'https://source.unsplash.com/800x600/?salamandre%20tachet%C3%A9e,wildlife'),
	('Crapaud commun', 'Bufo bufo', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tempérée', 'Carnivore', 'LC', 'Decreasing', 'Amphibien robuste très répandu en Europe, actif surtout la nuit.', 'https://source.unsplash.com/800x600/?crapaud%20commun,wildlife'),
	('Rainette arboricole d''Europe', 'Hyla arborea', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tempérée', 'Carnivore', 'LC', 'Decreasing', 'Petite rainette verte vive, grimpant grâce à ses ventouses digitales.', 'https://source.unsplash.com/800x600/?rainette%20arboricole%20deurope,wildlife'),
	('Salamandre maculée', 'Ambystoma maculatum', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tempérée', 'Carnivore', 'LC', 'Stable', 'Salamandre nord-américaine noire aux taches jaune vif, vivant sous les feuilles mortes.', 'https://source.unsplash.com/800x600/?salamandre%20macul%C3%A9e,wildlife'),
	('Grenouille des bois', 'Lithobates sylvaticus', 'Animalia', 'Chordata', 'Amphibia', 'Forêt tempérée', 'Carnivore', 'LC', 'Stable', 'Grenouille capable de survivre partiellement gelée durant l''hiver boréal.', 'https://source.unsplash.com/800x600/?grenouille%20des%20bois,wildlife'),
	('Dromadaire', 'Camelus dromedarius', 'Animalia', 'Chordata', 'Mammalia', 'Désert', 'Herbivore', 'LC', 'Decreasing', 'Grand mammifère adapté à la chaleur extrême, capable de stocker l''eau efficacement.', 'https://source.unsplash.com/800x600/?dromadaire,wildlife'),
	('Chameau de Bactriane', 'Camelus bactrianus', 'Animalia', 'Chordata', 'Mammalia', 'Désert', 'Herbivore', 'CR', 'Decreasing', 'Chameau à deux bosses des déserts froids d''Asie centrale, très rare à l''état sauvage.', 'https://source.unsplash.com/800x600/?chameau%20de%20bactriane,wildlife'),
	('Fennec', 'Vulpes zerda', 'Animalia', 'Chordata', 'Mammalia', 'Désert', 'Omnivore', 'LC', 'Stable', 'Petit renard du Sahara aux grandes oreilles dissipant la chaleur corporelle.', 'https://source.unsplash.com/800x600/?fennec,wildlife'),
	('Oryx d''Arabie', 'Oryx leucoryx', 'Animalia', 'Chordata', 'Mammalia', 'Désert', 'Herbivore', 'VU', 'Increasing', 'Antilope blanche du désert sauvée de l''extinction par des programmes de réintroduction.', 'https://source.unsplash.com/800x600/?oryx%20darabie,wildlife'),
	('Addax', 'Addax nasomaculatus', 'Animalia', 'Chordata', 'Mammalia', 'Désert', 'Herbivore', 'CR', 'Decreasing', 'Antilope saharienne quasi disparue à l''état sauvage, adaptée à l''aridité extrême.', 'https://source.unsplash.com/800x600/?addax,wildlife'),
	('Rat-kangourou du désert', 'Dipodomys deserti', 'Animalia', 'Chordata', 'Mammalia', 'Désert', 'Herbivore', 'LC', 'Stable', 'Petit rongeur capable de vivre sans jamais boire d''eau directement.', 'https://source.unsplash.com/800x600/?rat-kangourou%20du%20d%C3%A9sert,wildlife'),
	('Mouflon du désert', 'Ovis canadensis nelsoni', 'Animalia', 'Chordata', 'Mammalia', 'Désert', 'Herbivore', 'LC', 'Stable', 'Mouflon adapté aux terrains rocailleux arides du sud-ouest américain.', 'https://source.unsplash.com/800x600/?mouflon%20du%20d%C3%A9sert,wildlife'),
	('Chat des sables', 'Felis margarita', 'Animalia', 'Chordata', 'Mammalia', 'Désert', 'Carnivore', 'LC', 'Stable', 'Petit félin nocturne aux coussinets poilus protégeant du sable brûlant.', 'https://source.unsplash.com/800x600/?chat%20des%20sables,wildlife'),
	('Renard véloce', 'Vulpes velox', 'Animalia', 'Chordata', 'Mammalia', 'Désert', 'Omnivore', 'LC', 'Stable', 'Petit renard rapide des plaines arides nord-américaines.', 'https://source.unsplash.com/800x600/?renard%20v%C3%A9loce,wildlife'),
	('Gerboise du désert', 'Jaculus jaculus', 'Animalia', 'Chordata', 'Mammalia', 'Désert', 'Herbivore', 'LC', 'Stable', 'Petit rongeur sauteur aux longues pattes arrière, actif la nuit.', 'https://source.unsplash.com/800x600/?gerboise%20du%20d%C3%A9sert,wildlife'),
	('Grand géocoucou', 'Geococcyx californianus', 'Animalia', 'Chordata', 'Aves', 'Désert', 'Carnivore', 'LC', 'Stable', 'Oiseau coureur rapide du désert américain, chasseur de lézards et serpents.', 'https://source.unsplash.com/800x600/?grand%20g%C3%A9ocoucou,wildlife'),
	('Tétras des armoises', 'Centrocercus urophasianus', 'Animalia', 'Chordata', 'Aves', 'Désert', 'Herbivore', 'EN', 'Decreasing', 'Oiseau connu pour ses parades nuptiales spectaculaires dans les plaines arides.', 'https://source.unsplash.com/800x600/?t%C3%A9tras%20des%20armoises,wildlife'),
	('Troglodyte des cactus', 'Campylorhynchus brunneicapillus', 'Animalia', 'Chordata', 'Aves', 'Désert', 'Carnivore', 'LC', 'Stable', 'Petit oiseau bâtissant son nid dans les cactus épineux pour se protéger des prédateurs.', 'https://source.unsplash.com/800x600/?troglodyte%20des%20cactus,wildlife'),
	('Chevêche des terriers', 'Athene cunicularia', 'Animalia', 'Chordata', 'Aves', 'Désert', 'Carnivore', 'LC', 'Decreasing', 'Petite chouette nichant dans des terriers abandonnés de mammifères fouisseurs.', 'https://source.unsplash.com/800x600/?chev%C3%AAche%20des%20terriers,wildlife'),
	('Vautour percnoptère', 'Neophron percnopterus', 'Animalia', 'Chordata', 'Aves', 'Désert', 'Carnivore', 'EN', 'Decreasing', 'Petit vautour utilisant des outils pour briser les œufs d''autruche.', 'https://source.unsplash.com/800x600/?vautour%20percnopt%C3%A8re,wildlife'),
	('Ganga namaqua', 'Pterocles namaqua', 'Animalia', 'Chordata', 'Aves', 'Désert', 'Herbivore', 'LC', 'Stable', 'Oiseau capable de transporter de l''eau dans ses plumes ventrales pour ses poussins.', 'https://source.unsplash.com/800x600/?ganga%20namaqua,wildlife'),
	('Monstre de Gila', 'Heloderma suspectum', 'Animalia', 'Chordata', 'Reptilia', 'Désert', 'Carnivore', 'NT', 'Decreasing', 'Un des rares lézards venimeux au monde, se nourrissant d''œufs et de petits animaux.', 'https://source.unsplash.com/800x600/?monstre%20de%20gila,wildlife'),
	('Diable épineux', 'Moloch horridus', 'Animalia', 'Chordata', 'Reptilia', 'Désert', 'Carnivore', 'LC', 'Stable', 'Petit lézard australien couvert d''épines, se nourrissant exclusivement de fourmis.', 'https://source.unsplash.com/800x600/?diable%20%C3%A9pineux,wildlife'),
	('Crotale cornu sidewinder', 'Crotalus cerastes', 'Animalia', 'Chordata', 'Reptilia', 'Désert', 'Carnivore', 'LC', 'Stable', 'Serpent venimeux se déplaçant par ondulations latérales caractéristiques sur le sable chaud.', 'https://source.unsplash.com/800x600/?crotale%20cornu%20sidewinder,wildlife'),
	('Tortue du désert', 'Gopherus agassizii', 'Animalia', 'Chordata', 'Reptilia', 'Désert', 'Herbivore', 'VU', 'Decreasing', 'Tortue fouisseuse creusant des terriers profonds pour échapper à la chaleur extrême.', 'https://source.unsplash.com/800x600/?tortue%20du%20d%C3%A9sert,wildlife'),
	('Vipère à cornes du Sahara', 'Cerastes cerastes', 'Animalia', 'Chordata', 'Reptilia', 'Désert', 'Carnivore', 'LC', 'Stable', 'Petite vipère saharienne s''enfouissant dans le sable, ne laissant dépasser que ses yeux.', 'https://source.unsplash.com/800x600/?vip%C3%A8re%20%C3%A0%20cornes%20du%20sahara,wildlife'),
	('Iguane chuckwalla', 'Sauromalus ater', 'Animalia', 'Chordata', 'Reptilia', 'Désert', 'Herbivore', 'LC', 'Stable', 'Gros iguane se gonflant d''air pour se coincer dans les fissures rocheuses.', 'https://source.unsplash.com/800x600/?iguane%20chuckwalla,wildlife'),
	('Crotale diamantin de l''Ouest', 'Crotalus atrox', 'Animalia', 'Chordata', 'Reptilia', 'Désert', 'Carnivore', 'LC', 'Stable', 'Grand serpent à sonnette redouté des déserts du sud-ouest américain.', 'https://source.unsplash.com/800x600/?crotale%20diamantin%20de%20louest,wildlife'),
	('Boa des sables du Kenya', 'Eryx colubrinus', 'Animalia', 'Chordata', 'Reptilia', 'Désert', 'Carnivore', 'LC', 'Stable', 'Petit boa fouisseur passant la majeure partie de sa vie sous le sable.', 'https://source.unsplash.com/800x600/?boa%20des%20sables%20du%20kenya,wildlife'),
	('Phrynosome à cornes du Texas', 'Phrynosoma cornutum', 'Animalia', 'Chordata', 'Reptilia', 'Désert', 'Carnivore', 'LC', 'Decreasing', 'Lézard camouflé couvert d''épines, capable de projeter du sang depuis ses yeux.', 'https://source.unsplash.com/800x600/?phrynosome%20%C3%A0%20cornes%20du%20texas,wildlife'),
	('Uromastyx du désert', 'Uromastyx aegyptia', 'Animalia', 'Chordata', 'Reptilia', 'Désert', 'Herbivore', 'VU', 'Decreasing', 'Grand lézard herbivore à la queue épineuse, actif de jour dans la chaleur intense.', 'https://source.unsplash.com/800x600/?uromastyx%20du%20d%C3%A9sert,wildlife'),
	('Crapaud à pieds palmés', 'Scaphiopus couchii', 'Animalia', 'Chordata', 'Amphibia', 'Désert', 'Carnivore', 'LC', 'Stable', 'Amphibien passant la majorité de l''année enterré, n''émergeant qu''après les pluies.', 'https://source.unsplash.com/800x600/?crapaud%20%C3%A0%20pieds%20palm%C3%A9s,wildlife'),
	('Crapaud du désert de Sonora', 'Incilius alvarius', 'Animalia', 'Chordata', 'Amphibia', 'Désert', 'Carnivore', 'LC', 'Stable', 'Grand crapaud sécrétant une toxine puissante par ses glandes cutanées.', 'https://source.unsplash.com/800x600/?crapaud%20du%20d%C3%A9sert%20de%20sonora,wildlife'),
	('Cyprinodon de la Vallée de la Mort', 'Cyprinodon diabolis', 'Animalia', 'Chordata', 'Pisces', 'Désert', 'Omnivore', 'CR', 'Decreasing', 'Minuscule poisson endémique d''un unique trou d''eau thermale du désert du Nevada.', 'https://source.unsplash.com/800x600/?cyprinodon%20de%20la%20vall%C3%A9e%20de%20la%20mort,wildlife'),
	('Cyprinodon du désert', 'Cyprinodon macularius', 'Animalia', 'Chordata', 'Pisces', 'Désert', 'Omnivore', 'EN', 'Decreasing', 'Petit poisson résistant à des variations extrêmes de température et de salinité.', 'https://source.unsplash.com/800x600/?cyprinodon%20du%20d%C3%A9sert,wildlife'),
	('Panthère des neiges', 'Panthera uncia', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Carnivore', 'VU', 'Stable', 'Grand félin solitaire des hautes montagnes d''Asie centrale, très discret.', 'https://source.unsplash.com/800x600/?panth%C3%A8re%20des%20neiges,wildlife'),
	('Gorille des montagnes', 'Gorilla beringei beringei', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Herbivore', 'EN', 'Increasing', 'Grand primate vivant en petits groupes familiaux dans les forêts d''altitude d''Afrique centrale.', 'https://source.unsplash.com/800x600/?gorille%20des%20montagnes,wildlife'),
	('Bouquetin des Alpes', 'Capra ibex', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Herbivore', 'LC', 'Increasing', 'Caprin aux longues cornes recourbées, grimpeur agile des parois rocheuses alpines.', 'https://source.unsplash.com/800x600/?bouquetin%20des%20alpes,wildlife'),
	('Chèvre des montagnes Rocheuses', 'Oreamnos americanus', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Herbivore', 'LC', 'Stable', 'Caprin nord-américain au pelage blanc épais, expert des falaises escarpées.', 'https://source.unsplash.com/800x600/?ch%C3%A8vre%20des%20montagnes%20rocheuses,wildlife'),
	('Mouflon canadien', 'Ovis canadensis', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Herbivore', 'LC', 'Stable', 'Ovin sauvage aux cornes massives recourbées, célèbre pour ses combats de front.', 'https://source.unsplash.com/800x600/?mouflon%20canadien,wildlife'),
	('Chat des Andes', 'Leopardus jacobita', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Carnivore', 'EN', 'Decreasing', 'Petit félin très rare des hautes altitudes andines, l''un des chats les plus menacés.', 'https://source.unsplash.com/800x600/?chat%20des%20andes,wildlife'),
	('Vigogne', 'Vicugna vicugna', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Herbivore', 'LC', 'Increasing', 'Camélidé sauvage andin à la laine extrêmement fine et précieuse.', 'https://source.unsplash.com/800x600/?vigogne,wildlife'),
	('Tahr de l''Himalaya', 'Hemitragus jemlahicus', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Herbivore', 'NT', 'Decreasing', 'Caprin robuste des pentes escarpées himalayennes au pelage fourni.', 'https://source.unsplash.com/800x600/?tahr%20de%20lhimalaya,wildlife'),
	('Panda roux', 'Ailurus fulgens', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Herbivore', 'EN', 'Decreasing', 'Petit mammifère arboricole roux se nourrissant principalement de bambou en altitude.', 'https://source.unsplash.com/800x600/?panda%20roux,wildlife'),
	('Pika d''Amérique', 'Ochotona princeps', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Herbivore', 'LC', 'Decreasing', 'Petit lagomorphe des éboulis alpins, très sensible au réchauffement climatique.', 'https://source.unsplash.com/800x600/?pika%20dam%C3%A9rique,wildlife'),
	('Yak sauvage', 'Bos mutus', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Herbivore', 'VU', 'Decreasing', 'Grand bovidé au pelage épais, adapté aux hauts plateaux tibétains glacés.', 'https://source.unsplash.com/800x600/?yak%20sauvage,wildlife'),
	('Markhor', 'Capra falconeri', 'Animalia', 'Chordata', 'Mammalia', 'Montagne', 'Herbivore', 'NT', 'Increasing', 'Grande chèvre sauvage aux cornes torsadées spectaculaires en tire-bouchon.', 'https://source.unsplash.com/800x600/?markhor,wildlife'),
	('Condor des Andes', 'Vultur gryphus', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Carnivore', 'VU', 'Decreasing', 'Un des plus grands oiseaux volants au monde, planant sur les courants andins.', 'https://source.unsplash.com/800x600/?condor%20des%20andes,wildlife'),
	('Aigle royal', 'Aquila chrysaetos', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Carnivore', 'LC', 'Stable', 'Grand rapace puissant chassant marmottes et lièvres dans les massifs montagneux.', 'https://source.unsplash.com/800x600/?aigle%20royal,wildlife'),
	('Monal de l''Himalaya', 'Lophophorus impejanus', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Omnivore', 'LC', 'Stable', 'Faisan aux couleurs métalliques éclatantes, oiseau national du Népal.', 'https://source.unsplash.com/800x600/?monal%20de%20lhimalaya,wildlife'),
	('Gypaète barbu', 'Gypaetus barbatus', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Carnivore', 'NT', 'Increasing', 'Vautour unique se nourrissant principalement d''os, qu''il brise en les laissant tomber sur des rochers.', 'https://source.unsplash.com/800x600/?gypa%C3%A8te%20barbu,wildlife'),
	('Crave à bec rouge', 'Pyrrhocorax pyrrhocorax', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Omnivore', 'LC', 'Stable', 'Corvidé montagnard acrobate au bec et pattes rouge vif.', 'https://source.unsplash.com/800x600/?crave%20%C3%A0%20bec%20rouge,wildlife'),
	('Lagopède alpin', 'Lagopus muta', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Herbivore', 'LC', 'Decreasing', 'Oiseau changeant de plumage au fil des saisons pour se camoufler dans la neige.', 'https://source.unsplash.com/800x600/?lagop%C3%A8de%20alpin,wildlife'),
	('Tétraogalle de l''Himalaya', 'Tetraogallus himalayensis', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Herbivore', 'LC', 'Stable', 'Grand gallinacé des hautes altitudes himalayennes, difficile à observer.', 'https://source.unsplash.com/800x600/?t%C3%A9traogalle%20de%20lhimalaya,wildlife'),
	('Tichodrome échelette', 'Tichodroma muraria', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Carnivore', 'LC', 'Stable', 'Petit oiseau aux ailes rouge vif, grimpant les parois rocheuses verticales à la recherche d''insectes.', 'https://source.unsplash.com/800x600/?tichodrome%20%C3%A9chelette,wildlife'),
	('Condor de Californie', 'Gymnogyps californianus', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Carnivore', 'CR', 'Increasing', 'Le plus grand oiseau terrestre d''Amérique du Nord, sauvé de justesse de l''extinction.', 'https://source.unsplash.com/800x600/?condor%20de%20californie,wildlife'),
	('Aigle noir', 'Ictinaetus malaiensis', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Carnivore', 'LC', 'Stable', 'Grand rapace forestier de montagne d''Asie, chasseur d''oiseaux et petits mammifères.', 'https://source.unsplash.com/800x600/?aigle%20noir,wildlife'),
	('Perdrix des neiges', 'Lerwa lerwa', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Herbivore', 'LC', 'Stable', 'Petit gallinacé himalayen vivant près de la limite des neiges éternelles.', 'https://source.unsplash.com/800x600/?perdrix%20des%20neiges,wildlife'),
	('Accenteur alpin', 'Prunella collaris', 'Animalia', 'Chordata', 'Aves', 'Montagne', 'Omnivore', 'LC', 'Stable', 'Petit passereau discret nichant parmi les rochers des hautes altitudes européennes.', 'https://source.unsplash.com/800x600/?accenteur%20alpin,wildlife'),
	('Truite dorée de Californie', 'Oncorhynchus mykiss aguabonita', 'Animalia', 'Chordata', 'Pisces', 'Montagne', 'Carnivore', 'LC', 'Stable', 'Sous-espèce de truite arc-en-ciel aux couleurs dorées vives, endémique des lacs alpins.', 'https://source.unsplash.com/800x600/?truite%20dor%C3%A9e%20de%20californie,wildlife'),
	('Renard polaire', 'Vulpes lagopus', 'Animalia', 'Chordata', 'Mammalia', 'Toundra', 'Omnivore', 'LC', 'Stable', 'Petit canidé arctique changeant de couleur de pelage selon la saison.', 'https://source.unsplash.com/800x600/?renard%20polaire,wildlife'),
	('Renne', 'Rangifer tarandus', 'Animalia', 'Chordata', 'Mammalia', 'Toundra', 'Herbivore', 'VU', 'Decreasing', 'Cervidé arctique migrateur, seule espèce de cervidé dont les deux sexes portent des bois.', 'https://source.unsplash.com/800x600/?renne,wildlife'),
	('Bœuf musqué', 'Ovibos moschatus', 'Animalia', 'Chordata', 'Mammalia', 'Toundra', 'Herbivore', 'LC', 'Stable', 'Grand bovidé à l''épaisse toison, formant un cercle défensif face aux prédateurs.', 'https://source.unsplash.com/800x600/?b%C5%93uf%20musqu%C3%A9,wildlife'),
	('Lièvre arctique', 'Lepus arcticus', 'Animalia', 'Chordata', 'Mammalia', 'Toundra', 'Herbivore', 'LC', 'Stable', 'Grand lièvre au pelage blanc hivernal, adapté aux températures extrêmes.', 'https://source.unsplash.com/800x600/?li%C3%A8vre%20arctique,wildlife'),
	('Lemming de Norvège', 'Lemmus lemmus', 'Animalia', 'Chordata', 'Mammalia', 'Toundra', 'Herbivore', 'LC', 'Stable', 'Petit rongeur dont les populations connaissent des cycles d''explosion démographique spectaculaires.', 'https://source.unsplash.com/800x600/?lemming%20de%20norv%C3%A8ge,wildlife'),
	('Harfang des neiges', 'Bubo scandiacus', 'Animalia', 'Chordata', 'Aves', 'Toundra', 'Carnivore', 'VU', 'Decreasing', 'Grand hibou blanc arctique chassant lemmings et autres petits mammifères en plein jour.', 'https://source.unsplash.com/800x600/?harfang%20des%20neiges,wildlife'),
	('Lagopède des saules', 'Lagopus lagopus', 'Animalia', 'Chordata', 'Aves', 'Toundra', 'Herbivore', 'LC', 'Stable', 'Gallinacé arctique changeant de plumage du brun d''été au blanc hivernal.', 'https://source.unsplash.com/800x600/?lagop%C3%A8de%20des%20saules,wildlife'),
	('Bruant des neiges', 'Plectrophenax nivalis', 'Animalia', 'Chordata', 'Aves', 'Toundra', 'Herbivore', 'LC', 'Stable', 'Petit passereau nichant plus au nord que tout autre oiseau terrestre.', 'https://source.unsplash.com/800x600/?bruant%20des%20neiges,wildlife'),
	('Eider à duvet', 'Somateria mollissima', 'Animalia', 'Chordata', 'Aves', 'Toundra', 'Carnivore', 'NT', 'Decreasing', 'Grand canard marin arctique, dont le duvet est traditionnellement récolté pour l''isolation.', 'https://source.unsplash.com/800x600/?eider%20%C3%A0%20duvet,wildlife'),
	('Harelde kakawi', 'Clangula hyemalis', 'Animalia', 'Chordata', 'Aves', 'Toundra', 'Carnivore', 'VU', 'Decreasing', 'Petit canard plongeur arctique au chant distinctif, plongeant profondément pour se nourrir.', 'https://source.unsplash.com/800x600/?harelde%20kakawi,wildlife'),
	('Faucon gerfaut', 'Falco rusticolus', 'Animalia', 'Chordata', 'Aves', 'Toundra', 'Carnivore', 'LC', 'Stable', 'Le plus grand des faucons, chasseur redouté des toundras arctiques.', 'https://source.unsplash.com/800x600/?faucon%20gerfaut,wildlife'),
	('Bruant lapon', 'Calcarius lapponicus', 'Animalia', 'Chordata', 'Aves', 'Toundra', 'Herbivore', 'LC', 'Stable', 'Petit passereau migrateur nichant dans la toundra arctique en été.', 'https://source.unsplash.com/800x600/?bruant%20lapon,wildlife'),
	('Bécasseau maubèche', 'Calidris canutus', 'Animalia', 'Chordata', 'Aves', 'Toundra', 'Carnivore', 'NT', 'Decreasing', 'Petit limicole effectuant des migrations remarquables entre l''Arctique et l''hémisphère sud.', 'https://source.unsplash.com/800x600/?b%C3%A9casseau%20maub%C3%A8che,wildlife'),
	('Mouette blanche', 'Pagophila eburnea', 'Animalia', 'Chordata', 'Aves', 'Toundra', 'Omnivore', 'NT', 'Decreasing', 'Oiseau marin entièrement blanc vivant à la limite des glaces arctiques.', 'https://source.unsplash.com/800x600/?mouette%20blanche,wildlife'),
	('Oie des neiges', 'Anser caerulescens', 'Animalia', 'Chordata', 'Aves', 'Toundra', 'Herbivore', 'LC', 'Increasing', 'Grande oie migratrice nichant dans la toundra arctique en immenses colonies.', 'https://source.unsplash.com/800x600/?oie%20des%20neiges,wildlife'),
	('Hareng de l''Atlantique', 'Clupea harengus', 'Animalia', 'Chordata', 'Pisces', 'Océan', 'Omnivore', 'LC', 'Stable', 'Petit poisson grégaire filtreur de plancton, pilier des chaînes alimentaires marines.', 'https://source.unsplash.com/800x600/?hareng%20de%20latlantique,wildlife');

INSERT INTO SPECIES_REGIONS (species_id, region_id, presence) VALUES
	(1, 1, 'Resident'),
	(2, 1, 'Resident'),
	(3, 1, 'Resident'),
	(4, 1, 'Resident'),
	(5, 1, 'Resident'),
	(6, 1, 'Resident'),
	(7, 1, 'Resident'),
	(8, 1, 'Resident'),
	(9, 1, 'Resident'),
	(10, 1, 'Resident'),
	(11, 1, 'Resident'),
	(12, 1, 'Resident'),
	(13, 1, 'Resident'),
	(14, 1, 'Resident'),
	(15, 1, 'Resident'),
	(16, 1, 'Resident'),
	(17, 1, 'Resident'),
	(18, 1, 'Resident'),
	(19, 1, 'Resident'),
	(20, 1, 'Resident'),
	(21, 1, 'Resident'),
	(22, 1, 'Resident'),
	(23, 1, 'Resident'),
	(24, 1, 'Resident'),
	(25, 1, 'Resident'),
	(26, 1, 'Resident'),
	(27, 1, 'Resident'),
	(28, 1, 'Resident'),
	(29, 1, 'Resident'),
	(30, 1, 'Resident'),
	(31, 1, 'Resident'),
	(32, 1, 'Resident'),
	(33, 1, 'Resident'),
	(34, 1, 'Resident'),
	(35, 1, 'Resident'),
	(36, 1, 'Resident'),
	(37, 1, 'Resident'),
	(38, 1, 'Resident'),
	(39, 1, 'Resident'),
	(40, 1, 'Resident'),
	(41, 1, 'Resident'),
	(42, 1, 'Resident'),
	(43, 1, 'Resident'),
	(44, 1, 'Resident'),
	(45, 1, 'Resident'),
	(46, 1, 'Resident'),
	(47, 1, 'Resident'),
	(48, 1, 'Resident'),
	(49, 1, 'Resident'),
	(50, 1, 'Resident'),
	(51, 2, 'Resident'),
	(52, 5, 'Resident'),
	(53, 1, 'Resident'),
	(54, 4, 'Resident'),
	(55, 2, 'Resident'),
	(56, 5, 'Resident'),
	(57, 1, 'Resident'),
	(58, 4, 'Resident'),
	(59, 2, 'Resident'),
	(60, 5, 'Resident'),
	(61, 1, 'Resident'),
	(62, 4, 'Resident'),
	(63, 2, 'Resident'),
	(64, 5, 'Resident'),
	(65, 1, 'Resident'),
	(66, 4, 'Resident'),
	(67, 2, 'Resident'),
	(68, 5, 'Resident'),
	(69, 1, 'Resident'),
	(70, 4, 'Resident'),
	(71, 2, 'Resident'),
	(72, 5, 'Resident'),
	(73, 1, 'Resident'),
	(74, 4, 'Resident'),
	(75, 2, 'Resident'),
	(76, 5, 'Resident'),
	(77, 1, 'Resident'),
	(78, 4, 'Resident'),
	(79, 2, 'Resident'),
	(80, 5, 'Resident'),
	(81, 1, 'Resident'),
	(82, 4, 'Resident'),
	(83, 2, 'Resident'),
	(84, 5, 'Resident'),
	(85, 1, 'Resident'),
	(86, 4, 'Resident'),
	(87, 2, 'Resident'),
	(88, 5, 'Resident'),
	(89, 1, 'Resident'),
	(90, 4, 'Resident'),
	(91, 2, 'Resident'),
	(92, 5, 'Resident'),
	(93, 1, 'Resident'),
	(94, 4, 'Resident'),
	(95, 2, 'Resident'),
	(96, 5, 'Resident'),
	(97, 1, 'Resident'),
	(98, 4, 'Resident'),
	(99, 2, 'Resident'),
	(100, 5, 'Resident'),
	(101, 5, 'Resident'),
	(101, 8, 'Resident'),
	(102, 8, 'Resident'),
	(103, 5, 'Resident'),
	(103, 8, 'Resident'),
	(104, 8, 'Resident'),
	(105, 5, 'Resident'),
	(105, 8, 'Resident'),
	(106, 8, 'Resident'),
	(107, 5, 'Resident'),
	(107, 8, 'Resident'),
	(108, 8, 'Resident'),
	(109, 5, 'Resident'),
	(109, 8, 'Resident'),
	(110, 8, 'Resident'),
	(111, 5, 'Resident'),
	(111, 8, 'Resident'),
	(112, 8, 'Resident'),
	(113, 5, 'Resident'),
	(113, 8, 'Resident'),
	(114, 8, 'Resident'),
	(115, 5, 'Resident'),
	(115, 8, 'Resident'),
	(116, 8, 'Resident'),
	(117, 5, 'Resident'),
	(117, 8, 'Resident'),
	(118, 8, 'Resident'),
	(119, 5, 'Resident'),
	(119, 8, 'Resident'),
	(120, 8, 'Resident'),
	(121, 5, 'Resident'),
	(121, 8, 'Resident'),
	(122, 8, 'Resident'),
	(123, 5, 'Migratory'),
	(123, 8, 'Resident'),
	(124, 8, 'Resident'),
	(125, 5, 'Resident'),
	(125, 8, 'Resident'),
	(126, 8, 'Resident'),
	(127, 5, 'Resident'),
	(127, 8, 'Resident'),
	(128, 8, 'Resident'),
	(129, 5, 'Resident'),
	(129, 8, 'Resident'),
	(130, 8, 'Resident'),
	(131, 5, 'Resident'),
	(131, 8, 'Resident'),
	(132, 8, 'Resident'),
	(133, 5, 'Resident'),
	(133, 8, 'Resident'),
	(134, 8, 'Resident'),
	(135, 5, 'Resident'),
	(135, 8, 'Resident'),
	(136, 8, 'Resident'),
	(137, 5, 'Resident'),
	(137, 8, 'Resident'),
	(138, 8, 'Resident'),
	(139, 5, 'Resident'),
	(139, 8, 'Resident'),
	(140, 7, 'Resident'),
	(141, 3, 'Resident'),
	(142, 7, 'Resident'),
	(143, 3, 'Resident'),
	(144, 7, 'Resident'),
	(145, 3, 'Resident'),
	(146, 7, 'Resident'),
	(147, 3, 'Resident'),
	(148, 7, 'Resident'),
	(149, 3, 'Resident'),
	(150, 7, 'Resident'),
	(151, 3, 'Resident'),
	(152, 7, 'Resident'),
	(153, 3, 'Resident'),
	(154, 7, 'Resident'),
	(155, 3, 'Resident'),
	(156, 7, 'Resident'),
	(157, 3, 'Resident'),
	(158, 7, 'Resident'),
	(159, 3, 'Resident'),
	(160, 7, 'Resident'),
	(161, 3, 'Resident'),
	(162, 7, 'Resident'),
	(163, 3, 'Resident'),
	(164, 7, 'Resident'),
	(165, 3, 'Resident'),
	(166, 7, 'Resident'),
	(167, 3, 'Resident'),
	(168, 7, 'Resident'),
	(169, 3, 'Resident'),
	(170, 7, 'Migratory'),
	(171, 3, 'Resident'),
	(172, 7, 'Resident'),
	(173, 3, 'Resident'),
	(174, 7, 'Resident'),
	(175, 3, 'Resident'),
	(176, 7, 'Resident'),
	(177, 3, 'Resident'),
	(178, 7, 'Resident'),
	(179, 3, 'Resident'),
	(180, 2, 'Resident'),
	(181, 1, 'Resident'),
	(182, 2, 'Resident'),
	(183, 1, 'Resident'),
	(184, 2, 'Resident'),
	(185, 1, 'Resident'),
	(186, 2, 'Resident'),
	(187, 1, 'Resident'),
	(188, 2, 'Resident'),
	(189, 1, 'Resident'),
	(190, 2, 'Resident'),
	(191, 1, 'Resident'),
	(192, 2, 'Resident'),
	(193, 1, 'Resident'),
	(194, 2, 'Resident'),
	(195, 1, 'Resident'),
	(196, 2, 'Resident'),
	(197, 1, 'Resident'),
	(198, 2, 'Resident'),
	(199, 1, 'Resident'),
	(200, 2, 'Resident'),
	(201, 1, 'Resident'),
	(202, 2, 'Resident'),
	(203, 1, 'Resident'),
	(204, 2, 'Resident'),
	(205, 1, 'Resident'),
	(206, 2, 'Resident'),
	(207, 1, 'Resident'),
	(208, 2, 'Resident'),
	(209, 1, 'Resident'),
	(210, 7, 'Resident'),
	(211, 4, 'Resident'),
	(212, 3, 'Resident'),
	(213, 7, 'Resident'),
	(214, 4, 'Resident'),
	(215, 3, 'Resident'),
	(216, 7, 'Resident'),
	(217, 4, 'Resident'),
	(218, 3, 'Resident'),
	(219, 7, 'Resident'),
	(220, 4, 'Resident'),
	(221, 3, 'Resident'),
	(222, 7, 'Resident'),
	(223, 4, 'Resident'),
	(224, 3, 'Resident'),
	(225, 7, 'Resident'),
	(226, 4, 'Resident'),
	(227, 3, 'Resident'),
	(228, 7, 'Resident'),
	(229, 4, 'Resident'),
	(230, 3, 'Resident'),
	(231, 7, 'Resident'),
	(232, 4, 'Resident'),
	(233, 3, 'Resident'),
	(234, 7, 'Resident'),
	(235, 4, 'Resident'),
	(236, 3, 'Resident'),
	(237, 4, 'Resident'),
	(238, 3, 'Resident'),
	(239, 4, 'Resident'),
	(240, 3, 'Resident'),
	(241, 4, 'Resident'),
	(242, 3, 'Resident'),
	(243, 4, 'Migratory'),
	(244, 3, 'Migratory'),
	(245, 4, 'Resident'),
	(246, 3, 'Resident'),
	(247, 4, 'Migratory'),
	(248, 3, 'Resident'),
	(249, 4, 'Migratory'),
	(250, 8, 'Resident');
